// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.0
// source: fetcher.proto

package fetcher_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FetcherV1Client is the client API for FetcherV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FetcherV1Client interface {
	UpdateToken(ctx context.Context, in *UpdateTokenRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type fetcherV1Client struct {
	cc grpc.ClientConnInterface
}

func NewFetcherV1Client(cc grpc.ClientConnInterface) FetcherV1Client {
	return &fetcherV1Client{cc}
}

func (c *fetcherV1Client) UpdateToken(ctx context.Context, in *UpdateTokenRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/fetcher_v1.FetcherV1/UpdateToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FetcherV1Server is the server API for FetcherV1 service.
// All implementations must embed UnimplementedFetcherV1Server
// for forward compatibility
type FetcherV1Server interface {
	UpdateToken(context.Context, *UpdateTokenRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedFetcherV1Server()
}

// UnimplementedFetcherV1Server must be embedded to have forward compatible implementations.
type UnimplementedFetcherV1Server struct {
}

func (UnimplementedFetcherV1Server) UpdateToken(context.Context, *UpdateTokenRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateToken not implemented")
}
func (UnimplementedFetcherV1Server) mustEmbedUnimplementedFetcherV1Server() {}

// UnsafeFetcherV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FetcherV1Server will
// result in compilation errors.
type UnsafeFetcherV1Server interface {
	mustEmbedUnimplementedFetcherV1Server()
}

func RegisterFetcherV1Server(s grpc.ServiceRegistrar, srv FetcherV1Server) {
	s.RegisterService(&FetcherV1_ServiceDesc, srv)
}

func _FetcherV1_UpdateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FetcherV1Server).UpdateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fetcher_v1.FetcherV1/UpdateToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FetcherV1Server).UpdateToken(ctx, req.(*UpdateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FetcherV1_ServiceDesc is the grpc.ServiceDesc for FetcherV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FetcherV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fetcher_v1.FetcherV1",
	HandlerType: (*FetcherV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateToken",
			Handler:    _FetcherV1_UpdateToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fetcher.proto",
}
